# Generated by Django 4.0.1 on 2022-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_empleado_correo_alter_empleado_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandera',
            fields=[
                ('idBandera', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'bandera',
                'managed': True,
            },
        ),
    ]
